version: "3.3"

services:
  office-employee-back:
    container_name: office-employee-back
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./office-employee-back:/usr/src/app/office-employee-back
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      AUTH_KEY: 71edaca883dec81992441c2117a1f60b # Change key for production
      PORT: 8080
  db:
    image: mongo
    container_name: office-employee-db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    command: "--logpath=/dev/null"

volumes:
  mongodb:
